using System.Reflection;
#pragma warning disable CS7035 // The specified version string does not conform to the recommended format - major.minor.build.revision
// This code automatically generated by a template. Do not edit it directly.

// Version information for an assembly consists of the following four values:
//      Major Version
//      Minor Version
//      Build Number
//      Revision (Days since start of year)
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0.2020135")]
[assembly: AssemblyInformationalVersion("0.1" +
#if DEBUG
    " DEBUG")]
#else
    "")]
#endif
