using System.Reflection;
// This code automatically generated by a template. Do not edit it directly.

// Version information for an assembly consists of the following four values:
//      Major Version
//      Minor Version
//      Build Number
//      Revision (Days since start of year)
[assembly: AssemblyVersion("1.2.0")]
[assembly: AssemblyFileVersion("1.2.0.119")]
[assembly: AssemblyInformationalVersion("1.2" +
#if DEBUG
    " DEBUG")]
#else
    "")]
#endif
